### ISSUE TITLE
Claim Rewards Button

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#10]
In the rewards tab:

Need a button to claim rewards. It will claim rewards from the dpos contract by calling https://github.com/loomnetwork/loom-js/blob/master/src/dpos/dpos-user.ts#L290 (without args)

It should show the rewards the user is expected to receive by calling https://github.com/loomnetwork/loom-js/blob/master/src/dpos/dpos-user.ts#L321 (included in loom-js 1.40.1)

**Comment by Kanavs27** [comment]
Fixed
