### ISSUE TITLE
UI should not allow delegations on BONDING state

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#101]
The UI should not allow you to delegate while you made a delegation which is still BONDING. Throw an error message maybe or gray out the Delegate button with a tooltip

https://files.slack.com/files-pri/T7AB1S3LN-FGDUC126P/image.png

**Comment by yuneeksehgal** [comment]
![image](https://user-images.githubusercontent.com/23660413/53239307-b385f700-36c1-11e9-8a0f-df8d92de5546.png)
