### ISSUE TITLE
Hook up dashboard to the extdev cluster

### ISSUE THREAD

**Issue by enlight** [loomnetwork/dashboard#1015]
The extdev cluster is our public testnet for third-party devs, the dashboard should allow third-party devs to manage their deploy keys/acccounts on extdev, view balances etc. Though DPOS features are not available on extdev.

The deploy key management isn't supported by extdev yet, I'll need to enable that feature there first. But we can start by adding a config for extdev.

I'll find the relevant gateway addresses and update this issue.

**Comment by mattkanwisher** [comment]
Don’t think we need to force people to register their keys on extdev1
