### ISSUE TITLE
Validator Mgt: User info required for minimum LOOM token to Become a validator

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#1020]
![image](https://user-images.githubusercontent.com/23660413/61124724-484c8e00-a4c5-11e9-8ddc-c075b872011d.png)

**Comment by Kanavs27** [comment]
Necessary amount info added to the page
![image](https://user-images.githubusercontent.com/44959753/61450464-ccdf5680-a974-11e9-99a8-e5ab164d298c.png)
