### ISSUE TITLE
Failed Establishing mapping for new dappchain and metamask accounts

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#103]
**Steps:**
1, Create DappChain account first and then create a new metamask account then it is not allowing you to map

![image](https://user-images.githubusercontent.com/23660413/53239655-8b4ac800-36c2-11e9-9415-3d1972c7758d.png)

**Comment by redben** [comment]
@yuneeksehgal can you try again, this should be fixed.

**Comment by yuneeksehgal** [comment]
@redben The flow is much better now for mapping new accounts.
