### ISSUE TITLE
Retrieving all delegations is inefficient

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#104]
Currently we retrieve all the delegations of a user by iterating over the list of validators and calling CheckDelegation. This is inefficient. We are going to add an extra function on loomchain (https://github.com/loomnetwork/loomchain/issues/761) called CheckAllDelegations (or something along these lines). Once that's implemented, we'll want to replace the code in https://github.com/loomnetwork/dashboard/blob/develop/src/services/dposv2Utils.js#L142-L165 with a simple call to that function.

**Comment by redben** [comment]
ultimately there should be a middleman (micro)services that listens to changes on the chain and updates a snapshot cache. That way both loomchain and the ui stay simple. But then again it’s another deployable unit to maintain. It’s all about balance, horse sized duck or 100 duck sized horses :)
