### ISSUE TITLE
Show token contract mapping

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1059]
Gateway on loom-js  1.57.2 now has `listContractMappingsAsync`

**Comment by yuneeksehgal** [comment]
ETH address is missing, verified on dev pointing prod

![image](https://user-images.githubusercontent.com/23660413/61775319-592ac700-ae16-11e9-8f06-dcdac2547dc7.png)

**Comment by yuneeksehgal** [comment]
ETH address is now showing

![image](https://user-images.githubusercontent.com/23660413/61936282-06821400-afaa-11e9-8917-ba9fb4615a3f.png)
