### ISSUE TITLE
Add a message deprecating Ledger legacy

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1066]
Something like:
> This option is being deprecated. We recommend using Ledger via Metemask.

**Comment by yuneeksehgal** [comment]
Message been added when trying to use Ledger (Legacy) option 

![image](https://user-images.githubusercontent.com/23660413/61703963-540b4080-ad60-11e9-9856-7f512a81cd19.png)

![image](https://user-images.githubusercontent.com/23660413/61703973-58375e00-ad60-11e9-9192-a67c4c841001.png)
