### ISSUE TITLE
Fix validator page on mobile

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1085]
![9A3C718F-BAD7-44E1-A98A-3D38ECA6F5AE](https://user-images.githubusercontent.com/200361/61763612-27a70100-ae00-11e9-910d-fe18cf6e5f4f.jpeg)

**Comment by yuneeksehgal** [comment]
Looks good on iPhone and Android now
![image](https://user-images.githubusercontent.com/23660413/61778651-c3466a80-ae1c-11e9-8bf3-7fa45aa0f45b.png)
