### ISSUE TITLE
Alert user if tx runs out of gas

### ISSUE THREAD

**Issue by skogman** [loomnetwork/dashboard#1139]
When depositing ETH, check the status of the tx via etherscan and alert the user if the tx fails because of gas limitations.

**Comment by yuneeksehgal** [comment]
While checking this on dev I am not getting out of gas notification during ETH deposit

![image](https://user-images.githubusercontent.com/23660413/62612804-d893bc80-b925-11e9-9ee6-b753018fca0c.png)

**Comment by yuneeksehgal** [comment]
This is fixed on dev

![image](https://user-images.githubusercontent.com/23660413/62705706-917ff700-ba0b-11e9-90f8-0b7494522aea.png)
