### ISSUE TITLE
Stake balance is not correct

### ISSUE THREAD

**Issue by oragnejang** [loomnetwork/dashboard#118]
![image](https://user-images.githubusercontent.com/11746626/53307613-9af22880-38dd-11e9-9b18-d8652acc680c.png)
![image](https://user-images.githubusercontent.com/11746626/53307619-a7768100-38dd-11e9-9ffd-da86d39a702a.png)

I staked at 1983 loom to NGC_StakeX.
but Staked value is zero in the main screen.

I will never use this block chain,
I can not trust it.

And I also posted withdraw issue.(Disappeared my value and not fixed yet)

**Comment by bitcoin-buble** [comment]
> I will never use this block chain,

@oragnejang this is a little extreme! These issues are not to do with the blockchain but UI issues. I have a feeling this is similar to this issue: https://github.com/loomnetwork/dashboard/pull/117

**Comment by bitcoin-buble** [comment]
As a work around if you signout and sign back in again the balances should refresh.

**Comment by oragnejang** [comment]
Oh thanks to fix it. It working normal.
