### ISSUE TITLE
Delegation: show net amount

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1195]
We do not seem to subtract validator fee from the amount shown under each tier.

As reported by Janam
![EDC44CF6-9235-443D-9E78-583A8B7DC843](https://user-images.githubusercontent.com/200361/63778930-eda1b100-c90f-11e9-8051-289c60007a15.png)

**Comment by yuneeksehgal** [comment]
Works well now

![image](https://user-images.githubusercontent.com/23660413/64164879-9cd70e80-ce61-11e9-841a-636bf911032c.png)
