### ISSUE TITLE
Add an announcement space on the Validator list page

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1199]
- [x] A row, same size as validator rows
- [x] Between 9th and 10th Validator
- [x] content and state (on/off) toggle from config.announcements.validatorsPage

**Comment by yuneeksehgal** [comment]
Changes are looking good on Dev env pointing prod

Desktop View
![image](https://user-images.githubusercontent.com/23660413/64409340-57efe980-d0a6-11e9-97ce-ddc082c5965c.png)

Mobile View
![image](https://user-images.githubusercontent.com/23660413/64409362-60482480-d0a6-11e9-9116-118202a4accc.png)
