### ISSUE TITLE
Add announcements pop-up 

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1200]
- [x] content and state (on/off) toggle from config.announcements.popup
- [x] deactivated once the user closed it (do not pop up again untiul there's different content)

**Comment by yuneeksehgal** [comment]
**Desktop View**
![image](https://user-images.githubusercontent.com/23660413/64167166-47513080-ce66-11e9-9d52-f5e9feff55f9.png)

**Mobile View**
![image](https://user-images.githubusercontent.com/23660413/64167208-6223a500-ce66-11e9-8acd-07db678be355.png)
