### ISSUE TITLE
WalletConnect: No indication if user is still connected to MM mobile app

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#1211]
Txs getting stuck after app is remained idle for sometime. Unable to get Sign in request on MM mobile app. Question is how we figure out that it is still connected or not? 

![image](https://user-images.githubusercontent.com/23660413/64012960-62f1c980-cb3c-11e9-907e-f9f6f9f24d89.png)

**Comment by redben** [comment]
It only connects to get the signatures.
