### ISSUE TITLE
Feature: Rename Plasmachain to Basechain

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#1218]
Lets prepare a PR that changes the branding from Plasmachain to Basechain for the upcoming chain upgrade

**Comment by redben** [comment]
#1225

**Comment by yuneeksehgal** [comment]
**Findings where name change is not reflecting**

Account page
![image](https://user-images.githubusercontent.com/23660413/65663933-bc72e880-e055-11e9-9b58-4040ebf3e116.png)


After Depositing LOOM and ETH
![image](https://user-images.githubusercontent.com/23660413/65663949-c7c61400-e055-11e9-9662-438ad4341b11.png)

History page
![image](https://user-images.githubusercontent.com/23660413/65663968-d57b9980-e055-11e9-95a3-acd946b7217f.png)

Validators guide https://loomx.io/developers/en/validator.html
![image](https://user-images.githubusercontent.com/23660413/65664044-0e1b7300-e056-11e9-9304-9c2dda090849.png)

Staking Guide
![image](https://user-images.githubusercontent.com/23660413/65664061-170c4480-e056-11e9-8761-4c928a881afa.png)

FAQ's
![image](https://user-images.githubusercontent.com/23660413/65664072-1d9abc00-e056-11e9-9fc7-3f6cc8886321.png)

**Comment by yuneeksehgal** [comment]
Retesting Findings:

- [ ] Account page 

- [ ] After Depositing LOOM and ETH

- [ ] History page

- [ ] Validators guide https://loomx.io/developers/en/validator.html

- [ ] Staking Guide

- [ ] FAQ's
