### ISSUE TITLE
Update dev/deploy copy

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1224]
>Janam: 
On the "Deploy to Plasmachain" page, can we change this wording: In order to deploy contracts to PlasmaChain, you need to stake LOOM as payment to the validators. Could we make it: "In order to deploy contracts to Basechain, you need to pay LOOM to validators". Someone got confused with the word 'stake' - he assumed he needed to stake LOOM with a validator.

**Comment by yuneeksehgal** [comment]
Changes looks fine on dev
![image](https://user-images.githubusercontent.com/23660413/65659981-df4bcf80-e04a-11e9-9d30-deae69789f2c.png)
