### ISSUE TITLE
Add bounty page

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#1229]
Videos:
Tutorial video – 300K LOOM
Non-technical video – 100K LOOM

Articles:
Building an app with Unity – 300K LOOM
Using the Loom Transfer Gateway – 300K LOOM
Using Solidity for Loom – 200K LOOM
Deploying a dapp to Loom – 200K LOOM
Non-technical article – 100K LOOM

**Comment by yuneeksehgal** [comment]
Typo in Bounty page

![image](https://user-images.githubusercontent.com/23660413/65664859-dca3a700-e057-11e9-9a92-a224c8eb4a6c.png)

**Comment by yuneeksehgal** [comment]
Good to be closed.

![image](https://user-images.githubusercontent.com/23660413/65667058-93098b00-e05c-11e9-8d18-72eb79e6a124.png)
