### ISSUE TITLE
Once rewards are claimed it still shows unclaimed balance until the page is refreshed

### ISSUE THREAD

**Issue by cimtrae** [loomnetwork/dashboard#136]
Once "Claim Rewards" button is pressed it shows successful claim and balance but does not reduce the unclaimed to zero until the user refreshes the page.

**Comment by lukezhangstudio** [comment]
@Kanavs27 can you try reproducing this?

**Comment by Kanavs27** [comment]
@lukezhangstudio I am not able to reproduce this one as we are having no rewards on rewards tab

**Comment by yuneeksehgal** [comment]
This is fixed long back
