### ISSUE TITLE
Important: during withdraw if reject is pressed in metamask the balance is still reducing

### ISSUE THREAD

**Issue by cimtrae** [loomnetwork/dashboard#137]
If we start withdraw then we reject it in metamask then instead of just leaving the balance alone, the balance still reduces from plasmachain.

**Comment by lukezhangstudio** [comment]
Known issue. we'll have retry ability added very soon

**Comment by cimtrae** [comment]
The balance is reducing from plasmachain account. So whats happening to the
tokens? Are they stuck in some intermediate contract/step?

**Comment by cimtrae** [comment]
Per communication with the team a retry feature is coming to address this hopefully today.

**Comment by gakonst** [comment]
Duplicate of https://github.com/loomnetwork/dashboard/issues/66

**Comment by cimtrae** [comment]
I will close this as it's a duplicate of 66.
