### ISSUE TITLE
Cannot withdraw max Loom amount. Says insufficient funds 

### ISSUE THREAD

**Issue by cimtrae** [loomnetwork/dashboard#138]
When withdrawing max balance it kept saying insufficient funds. I had to try with one loom less for it to go through. So instead of 100 I would have to withdraw 99. Not sure if this is some fee related on plasmachain. But if this can't be avoided there should be some text on the page that shows that maximum withdrawable amount after the fee applied.

**Comment by lukezhangstudio** [comment]
@Kanavs27 can you reproduce this?

**Comment by Kanavs27** [comment]
@lukezhangstudio Withdraw is not working with my old account, But I am able to withdraw maximum with newly created DPOS and Metamask accounts.

**Comment by cimtrae** [comment]
Withdraw is not working for me as well. I have 0.1 eth in mainnet. Here's what I am seeing in console.

ithdraw failed, error:  Error: JsonRpcEngine - response has no error or result for request:
{
  "method": "eth_estimateGas",
  "params": [
    {
      "from:....

**Comment by yuneeksehgal** [comment]
Good to be closed
