### ISSUE TITLE
Show downtime record on validator management page

### ISSUE THREAD

**Issue by enlight** [loomnetwork/dashboard#1434]
Add a new card with the title `Statistics` to the `/validator-management` page. On this card display a table showing the downtime record for the current validator:
```
Missed Blocks
Period | Blocks Missed
P      120
P-1    1 / 4096
P-2    0 / 4096
P-3    4 / 4096
```
Add a refresh button to update the stats.

The relevant data can be obtained by calling the `DowntimeRecord` on the DPOSv3 contract deployed on loomchain. See the `dpos3 downtime-record` command implementation in the loom CLI for reference https://github.com/loomnetwork/loomchain/blob/de2b60a2b9e28373961b1442810037e9434f8bdb/cmd/loom/dposV3_commands.go#L658

**Comment by mimiiiz** [comment]
https://github.com/loomnetwork/dashboard/pull/1441

**Comment by enlight** [comment]
Resolved
