### ISSUE TITLE
Staked amount at top shows zero though at validator level balances are there.

### ISSUE THREAD

**Issue by cimtrae** [loomnetwork/dashboard#157]
Staked amount at top shows zero though at validator level balances are there.

**Comment by cimtrae** [comment]
This started happening on Chrome 72.0.3626.119 after the Ledge warning started displaying.

**Comment by lukezhangstudio** [comment]
Added a second try at loading the staking amounts. Going to investigate it further in loom-js.

**Comment by cimtrae** [comment]
This seems to have fixed in the latest updates to dashboard.

**Comment by cimtrae** [comment]
Do you want to close the issue or still research further as the latest updates seem to fix this?
