### ISSUE TITLE
Withdraw fails with the following error

### ISSUE THREAD

**Issue by cimtrae** [loomnetwork/dashboard#158]
![error](https://user-images.githubusercontent.com/1434603/53509008-c1e06400-3a6f-11e9-817f-6e70e8b22602.png)

**Comment by cimtrae** [comment]
Chrome Version 72.0.3626.119

**Comment by mattkanwisher** [comment]
please email support@loomx.io with your eth address and transaction hash. Also in about 2-3 hours we will have a new release that fixes a lot of these issues, if you want to wait and retry there
