### ISSUE TITLE
Security issue: Restore account modal has auto-complete enabled

### ISSUE THREAD

**Issue by fkbenjamin** [loomnetwork/dashboard#166]
Tested on Opera 58.0.3135.79:

The input field to enter the seed phrase as a returning user does not have auto-complete disabled. I tested it on Opera, and when revisiting the page, I can reselect my seed phrase from auto-complete dropdown.

This represents a critical vulnerability, since it enables anyone who has access to the browser to steal the plasma chain seed phrase. I believe this can be solved by setting the [autocomplete](https://www.w3.org/TR/2011/WD-html5-20110525/common-input-element-attributes.html#attr-input-autocomplete) attribute of the input field to `off`

**Comment by lukezhangstudio** [comment]
yea i noticed the same on opera. Fixing
