### ISSUE TITLE
Security issue: Signing out does not remove the seed phrase from state

### ISSUE THREAD

**Issue by fkbenjamin** [loomnetwork/dashboard#167]
After signing out of an account, the Plasma Chain seed phrase is not removed from the apps state. This can be reproduced by doing this:

1. Restore Account with seed phrase
2. Sign out of restored account
3. Click on 'Returning User' again
4. The seed phrase is in the input field although this should be cleared from state

This represents a critical vulnerability, since it enables anyone who has access to the browser to steal the plasma chain seed phrase. I would assume that after logging out, I need to reenter my seed phrase to have access.

**Comment by lukezhangstudio** [comment]
fixing

**Comment by fkbenjamin** [comment]
Thanks, I believe that [this function](https://github.com/loomnetwork/dashboard/blob/9cc6effbc80f9ca1bcc2578aabc8b0c461ae9696/src/store/dposStore.js#L138) should also remove `seeds` from state and it should work.
