### ISSUE TITLE
loom fees in small transation

### ISSUE THREAD

**Issue by Batmaxpt** [loomnetwork/dashboard#170]
Metamask in chrome Ver. 72.0.3626.119 64 bits

when i try put the las loom i got fees like these ex:, for deposit 2000 metamask ask me to pay these in fees -> AMOUNT + GAS FEE
1606.39 LOOM + 0.000397

...i dont know if is correlated with my problem i did a deposit and still not appear in plasmachain...

**Comment by mattkanwisher** [comment]
support requests should goto support@loomx.io, this repo is just for bug reports thanks
