### ISSUE TITLE
Disable metamask button when it’s not installed

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#177]

**Comment by redben** [comment]
Also maybe show a link to metamask page

**Comment by yuneeksehgal** [comment]
This button should open Metamask site on new tab 

![image](https://user-images.githubusercontent.com/23660413/59250131-028d7300-8c44-11e9-979b-27e10124244e.png)

**Comment by napongk** [comment]
https://github.com/loomnetwork/dashboard/pull/665 Waiting for merge here

**Comment by yuneeksehgal** [comment]
Fixed on Dev 👍
