### ISSUE TITLE
Opera: I got disconnected from the Ledger device but app is still showing connected

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#179]
![image](https://user-images.githubusercontent.com/23660413/53627597-dd459d80-3c2e-11e9-9623-3240ffefadd2.png)

**Comment by redben** [comment]
Actually even if you disconnect your wallet, you are still connected to ethereum.

**Comment by yuneeksehgal** [comment]
@redben In that case, we should display some sort to pop up telling the user that the wallet gets disconnected.
