### ISSUE TITLE
Opera: Function error when trying to open blocks with double click

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#187]
Video: https://slack-files.com/T7AB1S3LN-FGMNJB9AA-297b399198

**Comment by redben** [comment]
@yuneeksehgal I could not reproduce the error, could you retry on your side?

**Comment by yuneeksehgal** [comment]
@redben The error is not there anymore but double-clicking on any blocks makes the pop-ups closed immediately

**Comment by yuneeksehgal** [comment]
This is reproducible on prod

![image](https://user-images.githubusercontent.com/23660413/54014304-35861d80-41a2-11e9-9343-0b2ae5f82fd1.png)
