### ISSUE TITLE
Opera: Tooltip remains on the screen whenever we press withdraw and deposit buttons

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#188]
![image](https://user-images.githubusercontent.com/23660413/53628260-90fb5d00-3c30-11e9-83e7-b8603acee339.png)

**Comment by redben** [comment]
UI has changed and tooltip is not there anymore.

**Comment by yuneeksehgal** [comment]
This is fixed with new UI flow
