### ISSUE TITLE
withdraw failed

### ISSUE THREAD

**Issue by oragnejang** [loomnetwork/dashboard#210]
I just check the withdraw testing. because I lost my loom token when withdraw.
But It also failed withdraw to Metamask as below 
![image](https://user-images.githubusercontent.com/11746626/53774847-762c2f80-3f33-11e9-82d9-5b43f1889888.png)

**Comment by lukezhangstudio** [comment]
Don't worry, you can't lose tokens. Please email support@loomx.io with your details (eth address, browser version, etc). Github issues is for bug reports only.

**Comment by oragnejang** [comment]
This is bug.. cannot withdraw.....
