### ISSUE TITLE
Getting I am also getting "Transfer failed for unknown reason" after the latest updates 

### ISSUE THREAD

**Issue by cimtrae** [loomnetwork/dashboard#211]
I am also getting "Transfer failed for unknown reason" after today's updates. Chrome and Metmask. Multiple users are experiencing this and reported on Telegram. This is happening both on deposits and withdraws.

**Comment by lukezhangstudio** [comment]
More information required for a bug report. If you want to reach support, email support@loomx.io

**Comment by cimtrae** [comment]
So I logged in using seed. All the balances showed correctly. Then I tried transferring a small amount of Loom from mainnet. Right after I pressed deposit it said failed with unknown reason. Also then put some withdraw amount and pressed the withdraw. Same error.

**Comment by cimtrae** [comment]
I will contact support.
