### ISSUE TITLE
Make login bubble more obvious

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#22]
<img width="845" alt="screen shot 2019-02-14 at 5 50 08 pm" src="https://user-images.githubusercontent.com/3032/52785447-94b4ae80-308a-11e9-9d8d-966339fc06c5.png">

this is super unobvious that you need to login 
maybe make it a larger bubble

**Comment by Kanavs27** [comment]
Disabled tabs takes us login screen now
