### ISSUE TITLE
For most validators, Delegate button is disabled

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#243]
![image](https://user-images.githubusercontent.com/23660413/54014394-7e3dd680-41a2-11e9-980d-f405ad0e99e0.png)

**Comment by prashantpawar** [comment]
My research shows that it is disabled, because the logic says that the Delegate button is only enabled if the state is equal to 'Bonded'.

I am not sure what these states mean, but it is clearly possible to 'Delegate' your tokens to any of these validators who are in Bonding state.

**Comment by redben** [comment]
should be fixed by #256

**Comment by yuneeksehgal** [comment]
@redben Now for validators where we already delegate some tokens before, Delegate button stuck on loading state

![image](https://user-images.githubusercontent.com/23660413/54125546-51502480-442b-11e9-9ce3-ee8c6747a539.png)

**Comment by prashantpawar** [comment]
Seeing the same thing
