### ISSUE TITLE
After successful withdraw, the loading animation is keep running on the tab section

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#248]
![2019-03-08_15h50_27](https://user-images.githubusercontent.com/23660413/54023773-d2a18000-41bb-11e9-8c6d-f9a611d3d706.gif)

**Comment by redben** [comment]
@yuneeksehgal can you confirm that this has been resolved?

**Comment by Kanavs27** [comment]
Fixed
