### ISSUE TITLE
Certain nodes are not allowed to stake

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#25]
we need a list of nodes that you aren't allowed to stake to, like "plasma-0,plasma-1"

**Comment by gakonst** [comment]
IMO the best way to do this is to just hide our nodes from the UI (plasma0-3), or add a warning message.

**Comment by Kanavs27** [comment]
Fixed

![2019-02-15_16h00_17](https://user-images.githubusercontent.com/44959753/52851173-68a53600-313b-11e9-93d6-8c3f3ace66c6.png)

**Comment by mattkanwisher** [comment]
It is still allowing delegation to the bootstrap nodes

<img width="920" alt="screen shot 2019-02-17 at 6 15 50 pm" src="https://user-images.githubusercontent.com/3032/52911542-37199f80-32e0-11e9-83c4-973e27a3e0c1.png">

**Comment by yuneeksehgal** [comment]
We now disable delegating/undelegating on following validators

plasma-0
plasma-1
plasma-2
plasma-3
Validator #4

![image](https://user-images.githubusercontent.com/23660413/52945096-f761bf00-3396-11e9-8434-822dc200bad2.png)
