### ISSUE TITLE
Got few errors on this page when I am trying to change the metamask account

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#260]
Steps: I just logged in into Dpos and simply change the metamask account before clicking onto Metamask `Connect & sign via your browser or extension` button

![image](https://user-images.githubusercontent.com/23660413/54124560-c1a97680-4428-11e9-8912-2abd741fc1cf.png)

**Comment by yuneeksehgal** [comment]
This case is been handled. No error thrown now after changing the metamask account

**Comment by redben** [comment]
No longer relevant since we changed the way the user’s connects
