### ISSUE TITLE
Delegations with first Time Tier are automatically unlocked

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#296]
**Steps to reproduces:**
- make a delegation, any amount, choose first tier (2 weeks)

**Expected behaviour:**
Delegation unlocks in 2 weeks

**Actual behaviour:**
Delegation unlocked at time of creation

**Comment by yuneeksehgal** [comment]
This is fixed on staging

![image](https://user-images.githubusercontent.com/23660413/56490952-8bb9e080-6504-11e9-9b2b-0be14df5fac4.png)
