### ISSUE TITLE
DposV3 UI Adjustments

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#306]
DPOS V3 will introduec a bunch of changes that will be made in loom-js, w.r..t the return values of delegations (siince you'll be able ot hav emultiple delegations per validator), and other things.

Some UI components will need to be adjusted, I'll fill this issue up with any requested changes.

**Comment by redben** [comment]
Let’s add tickets for this here https://github.com/loomnetwork/dashboard/milestone/3
