### ISSUE TITLE
floating point error when attempting to withdraw 'all' 

### ISSUE THREAD

**Issue by lukezhangstudio** [loomnetwork/dashboard#321]
![image](https://user-images.githubusercontent.com/1289797/54868963-37202a00-4dcd-11e9-9600-402a0d8008c5.png)

quite possibly due to tiny rewards from 10 minute staking on small amounts. will need to do better rounding

**Comment by yuneeksehgal** [comment]
We are allowing upto 6 decimal places

![image](https://user-images.githubusercontent.com/23660413/60661632-f9c14300-9e77-11e9-980d-2e76da6bdf32.png)
