### ISSUE TITLE
Mobile UI: What value we need to show here instead of `{name}`

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#334]
![image](https://user-images.githubusercontent.com/23660413/55151654-bbc7cb00-5174-11e9-8a9e-d89d3dbbe740.png)

**Comment by yuneeksehgal** [comment]
@redben We need a space after with text

![image](https://user-images.githubusercontent.com/23660413/55230824-f306ac80-5246-11e9-8e35-e995c8c2b356.png)

**Comment by yuneeksehgal** [comment]
This is still reproducible on https://m-dashboard.dappchains.com

![image](https://user-images.githubusercontent.com/23660413/55384579-b2f64100-5548-11e9-8c8c-23f5ffb019e3.png)

**Comment by redben** [comment]
Fixed
![image](https://user-images.githubusercontent.com/200361/55393853-396e4b00-5568-11e9-8bc4-11877caebcc9.png)
