### ISSUE TITLE
Incorrect footer

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#34]
Seems to be using the wrong footer, the footer should look more like this 
<img width="222" alt="screen shot 2019-02-15 at 2 15 43 pm" src="https://user-images.githubusercontent.com/3032/52840560-3dffb100-312c-11e9-9068-748f11a68315.png">

**Comment by Kanavs27** [comment]
Fixed 

![2019-02-15_15h49_36](https://user-images.githubusercontent.com/44959753/52850373-53c7a300-3139-11e9-9cba-473c4ffadeaf.png)
