### ISSUE TITLE
Production site shouldn't allow blockchain selection

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#35]
hide the box for chain selection if the domain is "dashboard.dappchains.com"

<img width="465" alt="screen shot 2019-02-15 at 2 17 16 pm" src="https://user-images.githubusercontent.com/3032/52840638-756e5d80-312c-11e9-939e-265efed34fa2.png">

**Comment by Kanavs27** [comment]
Fixed
