### ISSUE TITLE
Feature Request: Stats Dashboard

### ISSUE THREAD

**Issue by lukezhangstudio** [loomnetwork/dashboard#351]
![image](https://user-images.githubusercontent.com/1289797/55305895-d22b9a80-5484-11e9-8f1f-49fa84a36fce.png)

![image](https://user-images.githubusercontent.com/1289797/55305867-c6d86f00-5484-11e9-853b-bfcd0e57e776.png)

**Comment by skogman** [comment]
Is the information for this available via the new API?

**Comment by yuneeksehgal** [comment]
![image](https://user-images.githubusercontent.com/23660413/61769251-452b9900-ae07-11e9-8a82-15bd614e1cc9.png)
