### ISSUE TITLE
mobile ui: during deposit flow, it's showing the history page link when only on step 1 (approve)

### ISSUE THREAD

**Issue by lukezhangstudio** [loomnetwork/dashboard#354]

**Comment by lukezhangstudio** [comment]
history page still isn't showing block confirmations on mobile and the link to it should not show up until the tx is confirmed in mainnet.

**Comment by yuneeksehgal** [comment]
This is fixed

![image](https://user-images.githubusercontent.com/23660413/55404645-ffa44100-5575-11e9-89f4-541059662093.png)
