### ISSUE TITLE
imToken: Deposit is getting failed

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#382]
![image](https://user-images.githubusercontent.com/23660413/55624244-f4922080-57c2-11e9-9573-28cc298526c6.png)

**Comment by redben** [comment]
should be fixed in https://github.com/loomnetwork/dashboard/pull/388

**Comment by yuneeksehgal** [comment]
Deposit is working but I am getting stuck on complete transfer screen. 

![video_13](https://user-images.githubusercontent.com/23660413/55787875-e13dc880-5ad4-11e9-8f53-bfa7e9bdcc28.gif)

**Comment by yuneeksehgal** [comment]
Deposit is working alright. Tried 3 deposit Txs on imToken app

![image](https://user-images.githubusercontent.com/23660413/56500721-9e92dc00-6529-11e9-97ff-5ecf50082a5c.png)
