### ISSUE TITLE
imToken: Resume Deposit is not working

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#383]
![image](https://user-images.githubusercontent.com/23660413/55624592-14761400-57c4-11e9-9361-89d4e3650900.png)

![image](https://user-images.githubusercontent.com/23660413/55624772-83536d00-57c4-11e9-808f-c30d9e21e6c3.png)

**Comment by redben** [comment]
should be fixed in https://github.com/loomnetwork/dashboard/pull/388

**Comment by redben** [comment]
duplicate  #364
