### ISSUE TITLE
imToken: Need to make block explorer page prettier

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#384]
![image](https://user-images.githubusercontent.com/23660413/55624813-9e25e180-57c4-11e9-92ee-3ceda4a2aecc.png)

**Comment by joe-bowman** [comment]
This is not just a mobile UI issue; this looks awful on a 4k resolution too. The resting postition of the closed transactions modal is visible on the RHS of the screen.

**Comment by redben** [comment]
This is being worked on on a seperate project.
