### ISSUE TITLE
Feature: Improve chain selection

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#414]
Chain selection is very hacky and not robust right now. We should switch to a typed config file which stores the addresses as follows:

```
{
  'chainName':  {
    "dappchainEndpoint" : "...",
    "chainId" : "..."
    "gatewayAddress" : "..."
   }
}
```

So for US1, it would be:

```
{
...other chains
   {
    "us1":  {
      "dappchainEndpoint" : "http://test-z-us1.dappchains.com",
      "mainnetEndpoint" : "https://rinkeby.infura.io",
      "chainId" : "default"
      "gatewayAddress" : "0x76c41eFFc2871e73F42b2EAe5eaf8Efe50bDBF73"
     }
  }
}
```

In addition, we should add an option for a user to specify a custom URL, in case they are running a local node at a different port than 46658 (such as when launching a cluster with the validators-tool)

**Comment by redben** [comment]
Done.
See https://github.com/loomnetwork/dashboard/pull/473
