### ISSUE TITLE
Error Dialogs can go away to quickly and they don't log to console

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#42]
The error dialog shouldn't disappear after 15 seconds. also there is no data in the console about it 

<img width="1290" alt="screen shot 2019-02-15 at 6 13 31 pm" src="https://user-images.githubusercontent.com/3032/52853289-bdea4300-314d-11e9-8af4-4f24eb99af6c.png">

**Comment by yuneeksehgal** [comment]
@skogman The error pop up still not remain on screen for 5 seconds.

**Comment by redben** [comment]
We should use a full blown pop up for the errors instead of the alert component.

**Comment by redben** [comment]
see #859
