### ISSUE TITLE
Redelagate has target validator AND optionally target delegation

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#440]
When the user chooses to redelegate, they should have a way to choose a target delegation in the target validator.

**Comment by yuneeksehgal** [comment]
This is not working for optionally target delegation.

**Steps:**

1, Open a Validator having few Delegations 
2, Click Redelegate button for any of the listed delegation
3, Select Target Validator like V2 which must be having some delegations as well
4, Now without selecting any delegation from the list, Click on Redelegate button

**Screen Shot**
![image](https://user-images.githubusercontent.com/23660413/57067574-0d6ff200-6ced-11e9-9a12-7e9b4df868d5.png)

**Video**
![2019-05-02_15h10_35](https://user-images.githubusercontent.com/23660413/57067595-182a8700-6ced-11e9-97b1-b4ebd7dc636b.gif)

**Comment by skogman** [comment]
It is now possible to redelegate without selecting a validator.

**Comment by yuneeksehgal** [comment]
@skogman Possible to redelegate without selecting a validator or delegation?

**Comment by yuneeksehgal** [comment]
I am still unable to redelegate if I do not select the Target validator's Delegation
![image](https://user-images.githubusercontent.com/23660413/57073009-57f96a80-6cfd-11e9-832a-afa64dc54104.png)

**Comment by redben** [comment]
From @gakonst 
> In other news, you’ll always have to call `Redelegate` with an `index` parameter, because you will have to choose a delegation from the source validator. It will always create a NEW delegation on the target validator now, so the `index`’s sole purpose is choosing which delegation to redelegate frmo the source validator.

**Comment by yuneeksehgal** [comment]
This is also fixed.
