### ISSUE TITLE
Deposit Flow: Initial needs to be caps in many places

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#442]
![image](https://user-images.githubusercontent.com/23660413/56280354-a288bd80-6127-11e9-90f3-125e42069e63.png)

![image](https://user-images.githubusercontent.com/23660413/56280361-aae0f880-6127-11e9-934b-d8b38b4b3a76.png)

![image](https://user-images.githubusercontent.com/23660413/56280466-eb407680-6127-11e9-9bac-766e38ae6170.png)

**Comment by yuneeksehgal** [comment]
Y needs to be in capitals
![image](https://user-images.githubusercontent.com/23660413/56488343-c1a69700-64fb-11e9-9ccc-a2abb9918c5b.png)

@redben The second and third screen shot findings from description is still pending

**Comment by redben** [comment]
Seems fixed
![image](https://user-images.githubusercontent.com/200361/57058555-cd077880-6cda-11e9-969e-abbe80f31a02.png)

**Comment by yuneeksehgal** [comment]
@redben These are still pending to be fixed
![image](https://user-images.githubusercontent.com/23660413/57063843-3474f680-6ce2-11e9-8955-5222ceb3c798.png)
