### ISSUE TITLE
US1: 403 error upon first attempt to login with metamask

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#451]
![image](https://user-images.githubusercontent.com/23660413/56342339-5c8a3300-61d5-11e9-9105-3980bdb47dc1.png)

**Comment by redben** [comment]
I could not reproduce this error could you check again @yuneeksehgal ?

**Comment by yuneeksehgal** [comment]
Still Reproducible on **dev-dashboard**

![image](https://user-images.githubusercontent.com/23660413/56486950-201d4680-64f7-11e9-92cd-27136c846346.png)

**Comment by redben** [comment]
https/http related
