### ISSUE TITLE
DPOSv3 Withdrawal asks to change account even though i am logged in with the correct account

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#458]
When I am withdrawing, I get the error about having to change an account, even though I am logged in with the correct account in metamask.

```A pending withdraw requires you to switch ETH accounts to: 0x6AE1C0890E9CF295FE164EDE614AB684175E68C0. Please change your account and then click OK```
(I am logged in already with that account in Metamask)
But the first part where it initializes the withdrawal works. Afterwards, when I click `OK`, I get the following:
`Uncaught (in promise) TypeError: this.switchDposUser is not a function`

**Comment by redben** [comment]
Should be fixed in [95ec528]
