### ISSUE TITLE
imToken: Withdraw is not working properly, end up in execute transfer screen

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#472]
Video Ref: https://slack-files.com/T7AB1S3LN-FJ4KF6D7Z-0e0d4f2605

Incomplete Withdraw also not working:
https://slack-files.com/T7AB1S3LN-FJ4KF6D7Z-0e0d4f2605

**Comment by redben** [comment]
Can you include more info like what do you see in your accounts history? Is the transaction there or not, if it is, is it confirmed or failed...etc

**Comment by yuneeksehgal** [comment]
This is fixed on Prod now
