### ISSUE TITLE
Prod: DappChain events list is not getting updated with latest entries

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#475]
![image](https://user-images.githubusercontent.com/23660413/56564709-511b7b00-65cc-11e9-8fe5-7de65c65414b.png)

**Comment by skogman** [comment]
It's not immediate, the indexer updates periodically. Nothing we can do about it from the UI side.

**Comment by yuneeksehgal** [comment]
@skogman As confirmed by Reda, it is loading the oldest transactions first instead of latest ones
