### ISSUE TITLE
Unable to complete, Incomplete Withdraw

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#503]
![2019-04-30_19h16_34](https://user-images.githubusercontent.com/23660413/56966603-0cb84e00-6b7d-11e9-8cfc-33a923e676ba.gif)

**Comment by redben** [comment]
For reference #488

**Comment by yuneeksehgal** [comment]
After trying to complete the incomplete Withdraw. I am still seeing `**Complete Withdraw**` button in My account page

In order to make this button vanished, I need to close the browser and relogin again.

Video Ref: https://slack-files.com/T7AB1S3LN-FJ0U1NE3U-1b9da2398b

**Comment by yuneeksehgal** [comment]
This is fixed in US1
