### ISSUE TITLE
Withdraw: eth_estimateGas error

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#51]
![image](https://user-images.githubusercontent.com/23660413/52932130-d4261800-3374-11e9-87ef-6a4ac7786cff.png)

Video Link: https://slack-files.com/T7AB1S3LN-FG8FQ8SDT-9008ae8796

**Comment by yuneeksehgal** [comment]
Happened with newly created accounts we well

![image](https://user-images.githubusercontent.com/23660413/53239713-b8977600-36c2-11e9-99e5-bfb48ecf84e0.png)

https://loom-network.slack.com/archives/CDF7X7UCB/p1550825530146800

**Comment by yuneeksehgal** [comment]
This is still exists on the dev build

![image](https://user-images.githubusercontent.com/23660413/53805257-ac87a000-3f6f-11e9-8f77-aa364a6821a3.png)

If we Initiate withdraw with the new account then getting the following error

![image](https://user-images.githubusercontent.com/23660413/53805335-da6ce480-3f6f-11e9-9423-0b346d00c459.png)

**Comment by redben** [comment]
This was due to bad arguments on contract function calls.
