### ISSUE TITLE
Typo in rewards tab

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#52]
Expected: receive

![image](https://user-images.githubusercontent.com/23660413/52932249-249d7580-3375-11e9-9055-71c518d1ae09.png)

**Comment by Kanavs27** [comment]
This is now fixed.

![image](https://user-images.githubusercontent.com/44959753/52945406-a56d6900-3397-11e9-99ce-c6ee1790ecce.png)
