### ISSUE TITLE
Change Blockexplorer tab name to "Block Explorer"

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#53]
![image](https://user-images.githubusercontent.com/23660413/52932925-8232c180-3377-11e9-81c0-0fca38fd8266.png)

**Comment by Kanavs27** [comment]
This is Fixed.

![image](https://user-images.githubusercontent.com/44959753/52945520-e8c7d780-3397-11e9-8cc4-662aa08c10fd.png)
