### ISSUE TITLE
Display user addresses on wallet page

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#532]
- account on eth as `eth:0x0000`
- account on plasma as `loom0000`

**Comment by yuneeksehgal** [comment]
@redben Was this for game-assets page or wallet page?

**Comment by yuneeksehgal** [comment]
Addresses are there in Wallet page now

![image](https://user-images.githubusercontent.com/23660413/59582532-3231f480-90f6-11e9-838b-c76bf3703cc3.png)
