### ISSUE TITLE
Display list of balances on plasmachain

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#533]
Each line has the following items:
- token name
- balance
- deposit button, to deposit from source chain 
- withdraw button, to withdraw to source chain
- swap button

**Comment by yuneeksehgal** [comment]
@redben I think we also need to show decimal values for balances.

**Comment by redben** [comment]
@yuneeksehgal closing since we now display decimal values
![image](https://user-images.githubusercontent.com/200361/59595520-2eb36300-9120-11e9-969e-d72444d50870.png)
