### ISSUE TITLE
In the top bar replace "DappChain" with "PlasmaChain" for consistency

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#54]
![image](https://user-images.githubusercontent.com/23660413/52933078-156bf700-3378-11e9-9f0a-1b798eba1c7b.png)

**Comment by Kanavs27** [comment]
This is also fixed.

![image](https://user-images.githubusercontent.com/44959753/52945640-36dcdb00-3398-11e9-85cf-0a37aba02d10.png)
