### ISSUE TITLE
Complete Withdraw button animation starts appearing after user rejects the Signature

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#541]
**Description**  
Complete Withdraw button animation starts appearing after user rejects the Signature

**Steps to reproduce the behavior:**
1.  Initiate Withdraw and on second Signature request , Reject the Sign in request

**Expected behavior**
Button animation should only starts appearing if user rejects the Txs not the Signature

**Screenshots/Videos**
![2019-05-13_15h44_13](https://user-images.githubusercontent.com/23660413/57621350-d7622600-75a8-11e9-96a4-8c7967291b1d.gif)

**Environment:**
 - Chrome/Metamask(Rinkeby)

**Comment by joe-bowman** [comment]
The same behaviour happens when you Claim Rewards - if the sign request is rejected, it tells you that you have successfully claimed the rewards.
