### ISSUE TITLE
Add a feedback form

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#545]

**Comment by yuneeksehgal** [comment]
@redben Feedback form is not getting reset after submitting it

![2019-05-24_15h41_50](https://user-images.githubusercontent.com/23660413/58321125-e794c380-7e3a-11e9-9652-f22f4f5d6c2a.gif)

**Comment by redben** [comment]
From Yuneek
> Give the user some feedback when the message is sent.
