### ISSUE TITLE
Feature: see who is delegating to each delegator

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#58]
Is it possible to show who all the delegations are ?

**Comment by mattkanwisher** [comment]
@gakonst

**Comment by skogman** [comment]
Pretty sure the delegator’s address is attached to the delegation object

**Comment by gakonst** [comment]
We will add a method for this on the backend. Currently not possible.

**Comment by redben** [comment]
Reopen when implemented upstream
