### ISSUE TITLE
Improvements to Withdraw workflow

### ISSUE THREAD

**Issue by joe-bowman** [loomnetwork/dashboard#581]
1) Display prominently that the Ethereum app needs the following settings to work:
 - Contract Data: ON
 - Display Data: OFF

2) Once you claim rewards, notify the user that the rewards will not show in claimed rewards (or add a pending rewards line) until the end of the next election

**Comment by lukezhangstudio** [comment]
we have a new improved UI that shows pending claims and such for item #2.

for item #1, when we get the ledger error for when users have contract data off, we display the suggestion to turn it on. Which wallet are you using that you're encountering this not happening? firmware version, and all that will help debugging
