### ISSUE TITLE
Front end deposit gets failed, but history page is showing its in progress

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#595]
**My Account Page:**
![image](https://user-images.githubusercontent.com/23660413/58553411-83a33e00-8232-11e9-9905-b7ad9305b18a.png)

**History Page**
![image](https://user-images.githubusercontent.com/23660413/58553441-96b60e00-8232-11e9-91c1-ef8ad28d0236.png)

**Comment by skogman** [comment]
Resolved
