### ISSUE TITLE
Need to attempt few times in order to claim rewards

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#609]
Environment: US1

Video Ref: https://loom-network.slack.com/files/U92QH19PB/FK7L0GM2L/2019-06-03_21h11_21.mp4

**Comment by yuneeksehgal** [comment]
This one still exists

Video Ref: https://slack-files.com/T7AB1S3LN-FKGG2B7T5-76dcb58856

**Comment by redben** [comment]
Rewards behave just like delegations and are only unbonded after the next election. We added a message saying exactly that.

**Comment by yuneeksehgal** [comment]
A message has been added after claiming rewards

![image](https://user-images.githubusercontent.com/23660413/60166475-e5010180-981e-11e9-88ed-be39d06bf0b0.png)
