### ISSUE TITLE
Loom address validation

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#611]
Loom address inputs:
- https://github.com/loomnetwork/dashboard/blob/typescript/src/views/AddKey.vue#L34
- https://github.com/loomnetwork/dashboard/blob/typescript/src/components/modals/TransferCardsModal.vue#L11
- https://github.com/loomnetwork/dashboard/blob/typescript/src/components/modals/TransferPacksModal.vue#L9

Options:
- just a validation function
- a input component for loom addresses

**Comment by yuneeksehgal** [comment]
We are not validating if loom address exists or not, Able to use dummy loom address with 44 char. 

![image](https://user-images.githubusercontent.com/23660413/59493699-11c12a80-8ea9-11e9-9570-e98391f866f5.png)

**Comment by redben** [comment]
@yuneeksehgal that address is technically valid, it's up to the user to double check if it is the one they want to send to.
