### ISSUE TITLE
Use ethers.js instead of web3

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#64]
> **Matt** [5:27 PM]
> Hrmm I don’t think we can skip using ethers
> Cause the DPoS code uses ethers

**Comment by gakonst** [comment]
No need for ethers usage, you can connect with Metamask directly with `createMetamaskUser` of DPOSUser. 

I would be happy to start converting our codebases to use ethers though.

**Comment by redben** [comment]
@gakonst Let’s keep this ticket open then, until no other priorities are on the queue

**Comment by lukezhangstudio** [comment]
closing for now
