### ISSUE TITLE
Redelegate bindings

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#65]
With this PR https://github.com/loomnetwork/loom-js/pull/218/files we add the feature for users to swap around their delegations to new validators

We want a redelegate from/to button in each validator page

You click on a validator, and it either lets you redelegate FROM them, TO another one
or it lets you redelegate FROM another one TO them

**Comment by redben** [comment]
It has been merged
for ref https://github.com/loomnetwork/dashboard/issues/72
