### ISSUE TITLE
FAQ: set default state to collapsed

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#651]
> Stephanie [4:20 PM]
We’d like to hide (or fold in) all answers when users enters the page so that they will be able to see all questions in the first few seconds. And then when they click on one question, it will unfold the answer right below.

**Comment by yuneeksehgal** [comment]
This is also fixed, All FAQ's are collapsed on page load.

![image](https://user-images.githubusercontent.com/23660413/59582607-6c9b9180-90f6-11e9-9584-025734c12076.png)
