### ISSUE TITLE
Game Assets: Invalid amount error upon transfer Packs

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#653]
Screen **Shots:**

![image](https://user-images.githubusercontent.com/23660413/59194156-b68bf100-8ba5-11e9-84cc-362c2b7a1f5f.png)

![image](https://user-images.githubusercontent.com/23660413/59194164-be4b9580-8ba5-11e9-8ce1-054ec7b87d8d.png)

**Comment by Kanavs27** [comment]
Getting Invalid Amount error when we try to transfer 5, 7, 9 type amount of packs

![image](https://user-images.githubusercontent.com/44959753/59197454-00c5a000-8baf-11e9-9858-75232dc75ef1.png)

**Comment by Kanavs27** [comment]
Fixed
