### ISSUE TITLE
Game Assets: Show in buttons are not working

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#654]
![image](https://user-images.githubusercontent.com/23660413/59194562-0a4b0a00-8ba7-11e9-881c-cfbc5a45e95d.png)

**Comment by Kanavs27** [comment]
@mimiiiz Loom tokens balance is not showing on Show in Block Explorer page

![2019-06-11_13h49_43](https://user-images.githubusercontent.com/44959753/59255902-70d83280-8c50-11e9-9331-917be57bef2e.png)

**Comment by yuneeksehgal** [comment]
@dnyopr The balance is still showing 0 in blockexplorer page

![image](https://user-images.githubusercontent.com/23660413/59488975-a70af180-8e9e-11e9-9d53-888cde288dcd.png)

**Comment by yuneeksehgal** [comment]
Both links are working on game-assets page
