### ISSUE TITLE
Game Assets: Initials needs to be in capitals

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#657]
![image](https://user-images.githubusercontent.com/23660413/59196590-b511f700-8bac-11e9-94f3-3e03d5b11172.png)

**Comment by Kanavs27** [comment]
@mimiiiz Can you please change initials in capitals for 'total amount'

![image](https://user-images.githubusercontent.com/44959753/59253507-04f3cb00-8c4c-11e9-8f95-512b83c07938.png)

**Comment by yuneeksehgal** [comment]
@dnyopr The changes are not reflecting on Dev

![image](https://user-images.githubusercontent.com/23660413/59488881-5c897500-8e9e-11e9-856d-886f4bec083e.png)

**Comment by yuneeksehgal** [comment]
Fixed this time 👍
