### ISSUE TITLE
Resume gateway withdrawal

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#66]
We want buttons that call https://github.com/loomnetwork/loom-js/blob/master/src/contracts/transfer-gateway.ts#L321 and https://github.com/loomnetwork/loom-js/blob/master/src/contracts/transfer-gateway.ts#L336.

The gateway dappchain contract is exposed through [`DPOSuser.dappchainGateway`](https://github.com/loomnetwork/loom-js/blob/master/src/dpos/dpos-user.ts#L180)

**Comment by redben** [comment]
```

**Comment by gakonst** [comment]
My bad.

Just make it call `reclaimDepositorTokensAsync()`

It should have no argument.

**Comment by oragnejang** [comment]
Where Can I find the reclaim Deposit button in dashboard?
