### ISSUE TITLE
Game Assets: Can't see packs/cards in front end after transfers

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#663]
**Steps:**

**Prerequisite:** User must have two metamask accounts, old one with packs and cards, New one without email associated with it also no packs and cards

1, Login with old metamask account in https://dev-dashboard.dappchains.com/en/login
2, Transfer some packs and cards into new metamask account loom address
3, Try to login with new mtamask account in stage.loom.games and check if you able to view packs and cards been transferred in step 2

Video Ref: https://screenpresso.com/=ZtjKd

**Comment by redben** [comment]
Is this related to the marketplace mapping problem?

**Comment by yuneeksehgal** [comment]
@redben Mimi could answer it better I think.

**Comment by mimiiiz** [comment]
` 2, Transfer some packs and cards into new metamask account loom address`
How do you know  loom address of new metamask account?

**Comment by yuneeksehgal** [comment]
@mimiiiz This is still not working for me, if you need call then please let me know

**Comment by redben** [comment]
@napongk can you check this again?

**Comment by yuneeksehgal** [comment]
After transferring few packs and cards, Cards are not showing in marketplace after performing transfers through dashbaord

https://slack-files.com/T7AB1S3LN-FL2UA36F5-a418d62587

**Comment by redben** [comment]
@yuneeksehgal This was a problem on staging only, contract addresses had changed.

**Comment by Kanavs27** [comment]
This is working well on Prod
