### ISSUE TITLE
Disappear after withdraw

### ISSUE THREAD

**Issue by oragnejang** [loomnetwork/dashboard#67]
I try to Withdraw in My account.
Insert value 7 in the "withdraw to Metamask" label.
Click the Withdraw button.
Click the reject Button in the MetaMask popup.

The 7 loom value can not recover, 
How can I find it?

**Comment by lukezhangstudio** [comment]
We'll add the ability to retry withdraw attempts soon. It's not lost, don't worry. I'll keep you updated.

**Comment by lukezhangstudio** [comment]
feature is being tracked on #66, closing to prevent duplication
