### ISSUE TITLE
Clarify between amount of staked tokens and voting power

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#73]
Currently the number shown validators's stake is actually their metadelegation (ie amount * bonus). We should rename `Stake` to `Voting Power`, and add an extra field which will be called `Tokens Delegated` which will show their actual amount of tokens delegated _without_ the bonuses. 

James' idea:

Total Stake | Total Voting Power* (*Staked tokens multiplied by lockup bonuses)

Parenthesis shows as a tooltip when you hover.
Also add information about how lockup multipliers work in the FAQ

LOOM-JS bindings: https://github.com/loomnetwork/loom-js/pull/219

**Comment by redben** [comment]
voting power column is gone
