### ISSUE TITLE
Show nodes that have been down for more then 8 hours

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#732]
Make nodes show up as greyed out and a RED down status next to their name if they are down for more then 8 hours. Use the DPoSv3 metrics apis to determine this

**Comment by redben** [comment]
@mattkanwisher by "greyed" you mean users cannot stake with them?

**Comment by redben** [comment]
For reference 
https://github.com/loomnetwork/loom-js/pull/292

**Comment by yuneeksehgal** [comment]
Recently missed blocks column has been added on Validators and details page

![image](https://user-images.githubusercontent.com/23660413/62117023-d489ee00-b2d8-11e9-8603-6696f65cd481.png)

![image](https://user-images.githubusercontent.com/23660413/62120630-980dc080-b2df-11e9-9bdd-1f1bcbbc296e.png)
