### ISSUE TITLE
Anything less then 5 minutes should display minutes and seconds ago

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#74]
Goal is to show the 1-3 second block times

I.e
5 seconds ago
2 minutes 7 seconds ago

<img width="1007" alt="screen shot 2019-02-21 at 12 54 25 pm" src="https://user-images.githubusercontent.com/3032/53144621-fc618100-35d7-11e9-9ccb-01904a6f98ba.png">

**Comment by lukezhangstudio** [comment]
not sure if we're using vue-blockexplorer as a submodule or not. this change might need to be made upstream or if it's made down here, we should upstream it. @HangYang @redben

**Comment by HangYang** [comment]
seems we copied vue-blockexplorer to this repo, so we can just change it here. moment.js  would be the fastest way to do it.
