### ISSUE TITLE
show deployed contract addresses on dev-deploy page

### ISSUE THREAD

**Issue by mimiiiz** [loomnetwork/dashboard#741]
https://github.com/loomnetwork/loom-js/blob/master/src/contracts/user-deployer-whitelist.ts#L107

- [x] UI
- [x] call contract

**Comment by nutchy** [comment]
![image](https://user-images.githubusercontent.com/13601750/60353973-67431e80-99f5-11e9-9535-78962a32dba8.png)

![image](https://user-images.githubusercontent.com/13601750/60353879-2e0aae80-99f5-11e9-903f-bbe09f2e9396.png)
when deployer click the address, should show the deployed contract address
