### ISSUE TITLE
Deploy to Plasmachain: Duplicate content while adding new key

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#753]
![image](https://user-images.githubusercontent.com/23660413/59748054-e8810f80-9297-11e9-9b6a-b4ec12a792f7.png)

**Comment by nutchy** [comment]
@yuneeksehgal it still duplicates? Can you try to test again

**Comment by yuneeksehgal** [comment]
Looks good now

![image](https://user-images.githubusercontent.com/23660413/60324492-91b7bc00-99a2-11e9-95c5-58c330f06891.png)
