### ISSUE TITLE
Undelegate: Unable to undelegate tokens

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#759]
Screen Shot:

![image](https://user-images.githubusercontent.com/23660413/59751205-c2f70480-929d-11e9-9b4c-033286983fd9.png)

**Comment by redben** [comment]
There was a few changes in the contract api. Should be back to normal tomorrow.

**Comment by redben** [comment]
See #760

**Comment by yuneeksehgal** [comment]
Good to be closed.
