### ISSUE TITLE
Developers -> Token Mappings

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#763]
Lets add a new diagnostic page under developers, that lists all the erc20/erc721 mappings that exist on the chain. In future we want to enable a way to enable doing erc20 mappings on this page but lets start with a simple diagnostic page

- [x] Add view
- [x] Add Action gatewayModule.getTokenContractLogs(contractAddress) 
- [x] paginate logs

**Comment by yuneeksehgal** [comment]
There is no validation Token name field and we need to switch between pages in order to see the entries again.

![2019-07-22_18h16_18](https://user-images.githubusercontent.com/23660413/61634225-82304800-acae-11e9-85a1-e46e34b6458d.gif)

**Comment by redben** [comment]
@yuneeksehgal there is no validation as there is no constraint on what a token symbol should be. 
I just retried and when you put the symbol of another token for which we have logs the logs show up again

**Comment by yuneeksehgal** [comment]
Good to be closed.
