### ISSUE TITLE
Update help/hint text

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#802]
#### Wallet
> Check your token balances,
> Deposit to Plasmachain from Ethereum
> Withdraw to Ethereum
> Transfer tokens to other PlasmaChain accounts
#### Game assets
> Check you Relentless assets (more coming soon)
> Transfer assets to other addresses
#### Deploy to Plasmachain
> In order to deploy contracts to PlasmaChain, you need to whitelist your deployment keys. You can manage your keys below, whitelist an existing key or generate a new one.
Adding a key requires you to stake tokens.

**Comment by lukezhangstudio** [comment]
bellow should be `below`
white list should be `whitelist`
Adding a key requires you to stake tokens

**Comment by yuneeksehgal** [comment]
Good to be closed.
