### ISSUE TITLE
History: Entries with 0 LOOM tokens were shown

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#827]
![image](https://user-images.githubusercontent.com/23660413/60155420-b1ff4380-9807-11e9-858a-2529bf944ba9.png)

**Comment by napongk** [comment]
you mean in history, a transaction list should not have transaction that done with 0 LOOM right?

**Comment by yuneeksehgal** [comment]
@napongk Yes, We cant perform any tx with 0 LOOM token.

**Comment by yuneeksehgal** [comment]
Fixed on Dev
