### ISSUE TITLE
Ledger: Mainnet ETH balance is not showing on Hardware wallet modal

### ISSUE THREAD

**Issue by yuneeksehgal** [loomnetwork/dashboard#871]
![image](https://user-images.githubusercontent.com/23660413/60271291-b6168880-990f-11e9-8ce2-0a0d68ba3f13.png)

**Comment by redben** [comment]
The provider was pointing to Rinkeby.

**Comment by yuneeksehgal** [comment]
Getting this error when trying to login with Ledger device

![image](https://user-images.githubusercontent.com/23660413/60585258-ea28f800-9dac-11e9-9383-290fcf5ff64c.png)

**Comment by yuneeksehgal** [comment]
This is still happening, Sometimes the balances are not getting loaded

![image](https://user-images.githubusercontent.com/23660413/60793717-e2d76500-a185-11e9-8ff9-ad9ac94000e9.png)

**Comment by yuneeksehgal** [comment]
Work now even if Ledger is not unlocked

![image](https://user-images.githubusercontent.com/23660413/61271549-9530ad00-a7c2-11e9-9f47-c941e526a6c9.png)
