### ISSUE TITLE
Remove hardcoded whitelist amounts

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#90]
In https://github.com/loomnetwork/dashboard/commit/16ebd59366ead8e5f81589580c28d26e32da32df whitelist amounts were hard-coded in order to ship things. 

Validators returned by `getValidatorsAsync` have their `whitelistAmount` accessible https://github.com/loomnetwork/loom-js/blob/master/src/contracts/dpos2.ts#L151.

**Comment by redben** [comment]
fixed
