### ISSUE TITLE
Show informational text on Validator Page

### ISSUE THREAD

**Issue by redben** [loomnetwork/dashboard#942]
If currently connected account is not a validator, show the user a text explaining how to become a validator.
> Matt
... let them know they need a balance of 1.25 million tokens to become a validator
have a link to the article on setting up a validator

**Comment by mattkanwisher** [comment]
The UI needs to have a way for the user to become a validator, and stake the 1.25 million tokens and register their private key as a validator

**Comment by mattkanwisher** [comment]
This doc shows how to setup a node https://loomx.io/developers/en/jump-start-plasma.html#download-stable-version-of-plasmachain

**Comment by yuneeksehgal** [comment]
We still dont have any text explaining how to become a validator including that they also require 1.25 million tokens to become a validator

**Comment by yuneeksehgal** [comment]
Relevant info is present on validator management page

![image](https://user-images.githubusercontent.com/23660413/61451785-da4a1000-a977-11e9-8631-c6ecda7dccf7.png)
