### ISSUE TITLE
Improve Withdrawal UX

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#97]
When users withdraw we should give them some UI response.

Currently all that happens is:
1. User clicks withdraw
... nothing happens for a while
2. User's dappchain balance gets reduced
... nothing happens for a while, user panics thinking they lost money
3. Metamask pops up
.. user clicks and gets funds

In between all the steps there should be some type of warning to the user about what they should be expecting to happen.

After 1 the user should see a message that is along the lines of "Your withdrawal is being initiated!"
After 2 they should see "PlasmaChain withdrawal initiated. Please wait for the Ethereum withdrawal confirmation dialog..."

**Comment by yuneeksehgal** [comment]
**Its now a 3 step process**

Step 1: Select amount

Step 2: Execute transfer
![image](https://user-images.githubusercontent.com/23660413/54337452-fbf75b80-4654-11e9-9464-97d64260aecf.png)


Step 3: Complete transfer
![image](https://user-images.githubusercontent.com/23660413/54337479-0ca7d180-4655-11e9-8bf1-b1b39a2d2172.png)

**Comment by yuneeksehgal** [comment]
@gakonst I think as per your suggestions, we still make some improvements in messages in various steps or we good with the current implementation?
