### ISSUE TITLE
UI breaks on refreshing at the delegations page

### ISSUE THREAD

**Issue by gakonst** [loomnetwork/dashboard#99]
Steps to reproduce:

1. Go to http://dev-dashboard.dappchains.com/en/delegations
2. Refresh
Should get infinite loomy loading page with error in the console: ```Error fetching delegation list: TypeError: Cannot read property 'listCandidatesAsync' of undefined```

Most likely related to the user object not being initialized during refresh for whatever reason

**Comment by redben** [comment]
The user session is now reset on refresh
